### PR TITLE
Context supports comments

### PR DESCRIPTION
**Pull request by jakethekoenig**
Context keeps track of and renders comments. Let me know what you think of the approach. Some questions:

* How should we render comments? I use 80*"-" because it's 1 token. It may be better to construct something using ┌ and rotations and |, -, to make box shapes. It uses more characters but it would certainly help the human read it. And I think very plausibly it may help the LLM.
* What should ragdaemon provide for people adding comments? This PR provides a basic interface for adding comments but I think it may make sense to make a few more specific utilities for adding comments from common formats. For instance it'd be nice to be able to turn the output of `pyright --outputjson` into inline comments. It'd also be nice to be able to take a list of github comments and render them. There's some creative freedom there though around where/if you put the author's name, how/where you render the timestamp etc.
* Currently my comment object accepts an endline but doesn't do anything with it. I'm not sure what the best way to handle it is. We could prefix all the commented lines with something like "|" but then it gets difficult if they overlap. We could also just say something in the comment text "This comment applies to lines 4-11".

### CODE REVIEW

**Comment by jakethekoenig** [comment]
I think the windows test failing is not because of this PR. It's from a test I didn't write for functionality I don't think I should have changed.

**Comment by biobootloader** [comment]
> How should we render comments? I use 80*"-" because it's 1 token. It may be better to construct something using ┌ and rotations and |, -, to make box shapes. It uses more characters but it would certainly help the human read it. And I think very plausibly it may help the LLM.

My guess would be that the box is just more confusing for the LLM. Maybe the best for an LLM would be to use xml tags like <github-comment> ... </github-comment>? Anthropic models are explicitly trained to understand them in prompts: https://docs.anthropic.com/claude/docs/use-xml-tags

> We could also just say something in the comment text "This comment applies to lines 4-11"

I think this is the best approach, as long as line numbers are being displayed

**Comment by jakethekoenig** [comment]
> > How should we render comments? I use 80*"-" because it's 1 token. It may be better to construct something using ┌ and rotations and |, -, to make box shapes. It uses more characters but it would certainly help the human read it. And I think very plausibly it may help the LLM.
> 
> My guess would be that the box is just more confusing for the LLM. Maybe the best for an LLM would be to use xml tags like `<github-comment> ... </github-comment>`? Anthropic models are explicitly trained to understand them in prompts: https://docs.anthropic.com/claude/docs/use-xml-tags
> 
> > We could also just say something in the comment text "This comment applies to lines 4-11"
> 
> I think this is the best approach, as long as line numbers are being displayed

Rewrote it to xml and it's definitely the right approach:
* Makes the code much simpler.
* Now comments with extra structure such as replies can encode it as subtrees themselves.
* Similarly the comment doesn't need to be aware of end line number. The caller can put it in the dictionary if they want.

**Comment by jakethekoenig** [comment]
> Rewrote it to xml and it's definitely the right approach:
> 
> * Makes the code much simpler.
> * Now comments with extra structure such as replies can encode it as subtrees themselves.
> * Similarly the comment doesn't need to be aware of end line number. The caller can put it in the dictionary if they want.

Thinking about it some more it's possible the ragdaemon side should be even simpler and only accept/store strings. And then it can be up to the callers to format their comments appropriately. I could see either way. If we really think xml is the right approach maybe it makes sense to be prescriptive about it and simplify our caller's job very marginally.

**Comment by granawkins** [comment]
I like being able to insert arbitrary text like this, and the xml thing is great.

`Comment` isn't really an annotator in the same sense as the others, so I think it should just be in ContextBuilder.

(Separately) I think there should be a `PullRequestAnnotator`, which loads the comments/replies/diffs/linked into the knowledge graph. Then you'd be able to add them with something like daemon.include(<pr_id>:<message_id>), they'd all be searchable/crawlable.

**Comment by jakethekoenig** [comment]
> (Separately) I think there should be a `PullRequestAnnotator`, which loads the comments/replies/diffs/linked into the knowledge graph. Then you'd be able to add them with something like daemon.include(<pr_id>:<message_id>), they'd all be searchable/crawlable.

That sounds like a good idea to me. Do you imagine ragdaeomon anything/scraping GitHub itself?

**Comment by jakethekoenig** [comment]
> `Comment` isn't really an annotator in the same sense as the others, so I think it should just be in ContextBuilder.

Moved it. I also added tags. I figured it might be important for users to be able to add pyright annotations and github annotations and then later just remove one of them.

**Comment by granawkins** [comment]
> > (Separately) I think there should be a `PullRequestAnnotator`, which loads the comments/replies/diffs/linked into the knowledge graph. Then you'd be able to add them with something like daemon.include(<pr_id>:<message_id>), they'd all be searchable/crawlable.
> 
> That sounds like a good idea to me. Do you imagine ragdaeomon anything/scraping GitHub itself? 
> 

Im not sure, hopefully we can use the authenticated setup from Butler somehow.

**Comment by jakethekoenig** [comment]
> Im not sure, hopefully we can use the authenticated setup from Butler somehow.

Oh yeah we could probably have it accept a repo, or pull object from the pygithub library and scrape/add everything from it.  Then it's super simple for callers in the case of public repos and not too complicated for private ones either. Would make it easy for butler to use.

**Pull request merged**
